title: QBF Workshop 2026
subtitle: International Workshop on Quantified Boolean Formulas and Beyond 2026
# email:
description: >- # this means to ignore newlines until "baseurl:"
  #International Workshop on Quantified Boolean Formulas and Beyond 2026 Â· Lisbon, Portugal

minimal_mistakes_skin: default
#search: true


markdown: kramdown
remote_theme: mmistakes/minimal-mistakes
layout: splash

include:
  - _pages

plugins:
  - jekyll-feed
  - jekyll-include-cache
